name: Deploy on Push

on:
  push:
    branches:
      - main
    paths:
      - 'youtube_app/**'                         # only when main_app/ changes
      - '.github/workflows/deploy-main.yml'  # re-run if you edit this workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (for context/version)
        uses: actions/checkout@v4

      - name: Deploy ADMIN app to servers
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }} # private key stored in secrets
          port: ${{ secrets.SERVER_SSH_PORT }} # optional, default 22
          script: |
            cd /opt/voicer-platform
            bash deploy-admin.sh
